export const TuningEnum = {
  SPOILER: 'Spoiler',
  FRONT_BUMPER: 'Zderzak przedni',
  REAR_BUMPER: 'Zderzak tylny',
  SIDE_SKIRT: 'Progi',
  EXHAUST: 'Wydech',
  FRAME: 'Klatka bezpieczeństwa',
  GRILLE: 'Grill',
  BONNET: 'Maska',
  LEFT_WING: 'Lewy błotnik',
  RIGHT_WING: 'Prawy błotnik',
  ROOF: 'Dach',
  ENGINE: 'Silnik',
  BRAKES: 'Hamulce',
  TRANSMISSION: 'Skrzynia biegów',
  SUSPENSION: 'Zawieszenie',
  TURBO: 'Turbo',
  PLATE_HOLDERS: 'Ramka tablicy',
  PLATE_VANITY: 'Dekoracja tablicy',
  TRIM_DESIGN: 'Wykończenie wnętrza',
  ORNAMENTS: 'Ozdoby',
  DASHBOARD: 'Deska rozdzielcza',
  DIAL_DESIGN: 'Zegary',
  DOOR_INTERIOR: 'Nagłośnienie w drzwiach',
  SEATS: 'Fotele',
  STEERING_WHEEL: 'Kierownica',
  SHIFT_LEVER: 'Gałka skrzyni biegów',
  PLAQUES: 'Tablice',
  REAR_SHELF: 'Nagłośnienie',
  TRUNK: 'Wnętrze bagażnika',
  ENGINE_BLOCK: 'Blok silnika',
  AIR_FILTER: 'Filter powietrza',
  STRUT_BAR: 'Rozpórka',
  ARCH_COVER: 'Osłona paska rozrządu',
  ANTENNA: 'Anteny',
  EXTERIOR_PARTS: 'Części zewnętrzne',
  TANK: 'Bak',
};
